import React, { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

export default function ChartSpine() {
  const pathRef = useRef(null);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    handleResize();
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    if (!pathRef.current) return;
    
    // Placeholder path for Phase 2 scaffolding.
    // In Phase 3, this will be dynamically generated by mapping over section milestones.
    const height = Math.max(document.body.scrollHeight, window.innerHeight * 2);
    const xPos = isMobile ? 20 : window.innerWidth / 2;
    // Simple straight line for testing the draw animation
    const pathString = `M ${xPos} 0 L ${xPos} ${height}`;
    
    pathRef.current.setAttribute('d', pathString);
    const length = pathRef.current.getTotalLength();
    
    pathRef.current.style.strokeDasharray = length;
    pathRef.current.style.strokeDashoffset = length;

    const animation = gsap.to(pathRef.current, {
      strokeDashoffset: 0,
      ease: 'none',
      scrollTrigger: {
        trigger: document.body,
        start: 'top top',
        end: 'bottom bottom',
        scrub: 1,
      }
    });

    return () => {
      animation.kill();
    };
  }, [isMobile]);

  return (
    <div className="pointer-events-none fixed top-0 left-0 h-[100vh] w-screen z-0 overflow-visible">
      <svg className="h-[100vh] w-full overflow-visible">
        <path
          ref={pathRef}
          fill="none"
          stroke="var(--chart-line, #D4FF00)"
          strokeWidth={isMobile ? "2" : "4"}
          className="transition-colors duration-1000 origin-top"
          style={{ vectorEffect: 'non-scaling-stroke' }}
        />
      </svg>
    </div>
  );
}
